local graphics_updater = require("__subterranio-base__/utilities/graphics-updater")
local constants = require("prototypes.entity.constants")

table.insert(data.raw["lab"]["lab"].inputs, "subterranean-science-pack")
table.insert(data.raw["lab"]["biolab"].inputs, "subterranean-science-pack")

table.insert(data.raw["furnace"]["stone-furnace"].crafting_categories, "smelting-or-metallurgy")
table.insert(data.raw["furnace"]["steel-furnace"].crafting_categories, "smelting-or-metallurgy")
table.insert(data.raw["furnace"]["electric-furnace"].crafting_categories, "smelting-or-metallurgy")
table.insert(data.raw["assembling-machine"]["foundry"].crafting_categories, "smelting-or-metallurgy")

table.insert(data.raw["technology"]["planet-discovery-aquilo"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["planet-discovery-aquilo"].prerequisites, "subterranean-science-pack")

table.insert(data.raw["technology"]["quantum-processor"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["captive-biter-spawner"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["foundation"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["fusion-reactor"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["fusion-reactor-equipment"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["legendary-quality"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["railgun"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["railgun-damage-1"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["promethium-science-pack"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["research-productivity"].unit.ingredients, {"subterranean-science-pack", 1})

table.insert(data.raw["technology"]["tunnelling-drill-equipment"].effects, {type = "unlock-space-location", space_location = "subterrain", use_icon_overlay_constant = true})

table.insert(data.raw["technology"]["mineshaft-belt"].prerequisites, "subterranean-science-pack")
table.insert(data.raw["technology"]["mineshaft-belt"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["fast-mineshaft-belt"].prerequisites, "subterranean-science-pack")
table.insert(data.raw["technology"]["fast-mineshaft-belt"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["express-mineshaft-belt"].prerequisites, "subterranean-science-pack")
table.insert(data.raw["technology"]["express-mineshaft-belt"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["turbo-mineshaft-belt"].prerequisites, "subterranean-science-pack")
table.insert(data.raw["technology"]["turbo-mineshaft-belt"].unit.ingredients, {"subterranean-science-pack", 1})
table.insert(data.raw["technology"]["mineshaft-pipe"].prerequisites, "subterranean-science-pack")
table.insert(data.raw["technology"]["mineshaft-pipe"].unit.ingredients, {"subterranean-science-pack", 1})

graphics_updater.update_entity_graphics("mining-drill", "electric-mining-drill", "electric-mining-drill", "mining-drill", "diamond-tipped-electric-mining-drill", constants.diamond_tint_color)
graphics_updater.update_entity_graphics("mining-drill", "big-mining-drill", "big-mining-drill", "mining-drill", "big-diamond-tipped-mining-drill", constants.diamond_tint_color)
graphics_updater.update_entity_graphics("assembling-machine", "crusher", "", "assembling-machine", "diamond-tipped-crusher", constants.diamond_tint_color)
