return {
    boron_chunk_path = "__subterranio-fulgora__/graphics/entity/boron-chunk.png",
    boron_chunk_size = 256,
    boron_powder_path = "__subterranio-fulgora__/graphics/entity/boron-powder.png",
    boron_powder_size = 256,
    cobalt_ore_path = "__subterranio-fulgora__/graphics/entity/cobalt-ore.png",
    cobalt_ore_size = 256,
    cobalt_plate_path = "__subterranio-fulgora__/graphics/entity/cobalt-plate.png",
    cobalt_plate_size = 256,
    diamond_image_path = "__subterranio-fulgora__/graphics/entity/diamond.png",
    diamond_image_size = 256,
    electromagnet_path = "__subterranio-fulgora__/graphics/entity/electromagnet.png",
    electromagnet_size = 256,
    electrostatic_shielding_path = "__subterranio-fulgora__/graphics/entity/electrostatic-shielding.png",
    electrostatic_shielding_size = 256,
    holmium_cabling_path = "__subterranio-fulgora__/graphics/entity/holmium-cabling.png",
    holmium_cabling_size = 256,
    induction_science_pack_path = "__subterranio-fulgora__/graphics/entity/induction-science-pack.png",
    induction_science_pack_size = 256,
    magnetic_bearings_path = "__subterranio-fulgora__/graphics/entity/magnetic-bearings.png",
    magnetic_bearings_size = 256,
    magnetic_casing_path = "__subterranio-fulgora__/graphics/entity/magnetic-casing.png",
    magnetic_casing_size = 256,
    magnetic_packaging_path = "__subterranio-fulgora__/graphics/entity/magnetic-packaging.png",
    magnetic_packaging_size = 256,
    magnetic_shielding_path = "__subterranio-fulgora__/graphics/entity/magnetic-shielding.png",
    magnetic_shielding_size = 256,
    neodymium_path = "__subterranio-fulgora__/graphics/entity/neodymium.png",
    neodymium_size = 256,
    neodymium_magnet_path = "__subterranio-fulgora__/graphics/entity/neodymium-magnet.png",
    neodymium_magnet_size = 256,
    neodymium_powder_path = "__subterranio-fulgora__/graphics/entity/neodymium-powder.png",
    neodymium_powder_size = 256,

    fulgoran_subway_tint = { r= 1.0, g = 0.3, b = 0.75, a = 1.0 },
}
