require("lib.data-stage")

require("prototypes.entities.advanced-chemical-plant")
require("prototypes.entities.boron")
require("prototypes.entities.cobalt")
require("prototypes.entities.electromagnets")
require("prototypes.entities.electrostatic-shielding")
require("prototypes.entities.fulgoran-gate")
require("prototypes.entities.fulgoran-lamp")
require("prototypes.entities.fulgoran-wall")
require("prototypes.entities.holmium-cabling")
require("prototypes.entities.induction-furnace")
require("prototypes.entities.induction-science-pack")
require("prototypes.entities.ion-thrusters")
require("prototypes.entities.maglev-rails")
require("prototypes.entities.magnetic-asteroid-collector")
-- require("prototypes.entities.magnetic-bearings")
require("prototypes.entities.magnetic-component-processing")
require("prototypes.entities.magnetic-shielding")
require("prototypes.entities.neodymium")
require("prototypes.entities.refined-speed-module")
require("prototypes.entities.scraps")
require("prototypes.entities.transformer-station")

require("prototypes.item.electrostatic-tunnelling-drill-equipment")
require("prototypes.item.subgroups")

require("prototypes.surfaces.subterranean-surface")
require("prototypes.surfaces.subway-noise-expressions")

require("prototypes.tiles.subway-fulgoran-paving")
